baseURL: "https://blog.issyrup.tech/"
title: Syrup
paginate: 5
theme: PaperMod

enableEmoji: true

enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false

outputs:
  home:
    - HTML
    - RSS
    - JSON

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "Syrup's blog"
  description: "My personal blog"
  keywords: [Blog, Portfolio]
  author: Syrup
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicon.ico"
    favicon16x16: "/favicon16x16.ico"
    favicon32x32: "/favicon32x32.ico"
    apple_touch_icon: "/favicon.ico"
    # safari_pinned_tab: "<link / abs url>"

  # label:
  #  text: "Home"
  #  icon: /apple-touch-icon.png
  #  iconHeight: 35


  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hey there! Syrup is here! 😄👋"
    
    Content: >
     Welcome to my personal blog! 🎉
    
      - I'm really excited to share with you some of the things I've learned, including tutorials, tips, and tricks that I hope will be helpful to you.
    
      - Please bear with me, as this is my first attempt at creating a blog, and I'm still learning. 🙏
      
      - I appreciate your visit and hope you enjoy what I have to offer. 😊

      - Thank you for stopping by! 🌟

  socialIcons:
    # - name: twitter
      # url: "https://twitter.com/"
    # - name: stackoverflow
      # url: "https://stackoverflow.com"
    - name: github
      url: "https://github.com/Syrup"

  #analytics:
  #  google:
  #    SiteVerificationTag: "XYZabc"
  #  bing:
  #    SiteVerificationTag: "XYZabc"
  #  yandex:
  #    SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/Syrup/syrup-hugo/blob/master/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: search
      name: Search
      url: /search/
      weight: 10
    - identifier: categories
      name: categories
      url: /categories/
      weight: 11
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    # - identifier: example
    #   name: example.org
    #   url: https://example.org
    #   weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    # noClasses: false
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: dracula